#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright contributors to the vLLM project
"""
Generate per-shape TensileLite tuning YAMLs for gfx908 INT8 W8A8 GEMMs.

The Qwen3.5-9B W8A8 dispatcher always invokes
``torch._int_mm(a [M, K] int8, b [K, N] int8) -> [M, N] int32``. On ROCm
this maps to the canonical hipBLASLt INT8 contraction
``Cijk_Ailk_Bljk_I8_BH``: row-major × col-major × INT32 dest, with
HighPrecisionAccumulate.

The YAML emitted here matches that contraction. Per-host gotchas:
  - HardwareMonitor: False (rocm-smi64 segfaults on this MI100 host;
    documented in library/m2-build-artifacts.md).
  - Do NOT include PrintSolutionRejectionReason — Tensile v5.0.0 warns
    about the unrecognised key.
  - DataType: I8 / DestDataType: I (int32) / ComputeDataType: I (int32).
  - MatrixInstruction: gfx908 supports v_mfma_i32_16x16x16i8 and
    v_mfma_i32_32x32x8i8. We tune over a small grid of MT/DepthU
    combinations targeting the W8A8 hot shapes.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from textwrap import dedent

# gfx908 has v_mfma_i32_16x16x16i8 (mfma 16) and v_mfma_i32_32x32x8i8 (mfma 32).
# We tune over a moderate grid: macro-tile ∈ {64, 128} on M; {64, 128} on N;
# DepthU ∈ {32, 64}. This keeps tuning under a few minutes per shape while
# still covering the dominant gfx908 INT8 GEMM regimes.
TUNING_YAML_TMPL = dedent("""\
################################################################################
# AUTO-GENERATED by scripts/mi100/gen_tensilelite_configs.py
# DO NOT EDIT MANUALLY — re-run the generator with an updated shape manifest.
#
# Shape: M={M}, N={N}, K={K} (batch=1)
# Problem type: Cijk_Ailk_Bljk_I8 (row-major × col-major INT8 × INT32 acc)
#               TransposeA=False, TransposeB=False (matches prebuilt
#               I8I8_II8_Ailk_Bljk operationIdentifier).
################################################################################

GlobalParameters:
  # NumElementsToValidate: 0 skips Tensile's reference-vs-kernel validation
  # path. We do our own end-to-end correctness in
  # tests/kernels/quantization/test_hipblaslt_int8_correctness.py once the
  # tuned logic YAMLs are loaded by hipBLASLt at runtime, so we don't need
  # the duplicate (and INT32-validator-buggy-at-this-scale) tuning-time
  # validation.
  NumElementsToValidate: 0
  KernelTime: True
  NewClient: 2
  BoundsCheck: False
  ValidationMaxToPrint: 4
  ValidationPrintValids: False
  PruneSparseMode: 0
  PrintWinnersOnly: True
  MinKForGSU: 1
  # rocm-smi64 segfaults on this MI100 host — see library/m2-build-artifacts.md
  HardwareMonitor: False

BenchmarkProblems:
  - # Cijk_Ailk_Bljk_I8 with INT32 acc / INT32 dest (matches the prebuilt
    # hipBLASLt I8I8_II8 contraction at
    # /root/hipblaslt-src/build/release/hipblaslt-install/lib/hipblaslt/library/
    # which is what torch._int_mm dispatches to on ROCm
    # (cType=Int32, dType=Int32, transA=False, transB=False at runtime).
    -
      OperationType: GEMM
      DataType: I8
      DestDataType: I
      ComputeDataType: I
      HighPrecisionAccumulate: True
      TransposeA: False
      TransposeB: False
      UseBeta: True
      Batched: True
    -
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - KernelLanguage: ["Assembly"]
      ForkParameters:
        - MatrixInstruction:
{matrix_instr_block}
        - DepthU: [32, 64]
        - TransposeLDS: [-1]
        - LdsPadA: [-1]
        - LdsPadB: [-1]
        - LdsPadMetadata: [0]
        - StaggerU: [0]
        - ScheduleIterAlg: [3]
        - PrefetchLocalRead: [1]
        - PrefetchGlobalRead: [1, 2]
        - StoreRemapVectorWidth: [0]
        - GlobalSplitU: [1, 2]
        - GlobalSplitUAlgorithm: [MultipleBuffer]
        - 1LDSBuffer: [-1]
        - DirectToVgprSparseMetadata: [0]
        - WorkGroupMapping: [1, 4, 8]
        - StoreVectorWidth: [-1]
      BenchmarkForkParameters:
      JoinParameters:
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Exact: [{M}, {N}, 1, {K}]   # M, N, batch, K

LibraryLogic:
    ScheduleName: "arcturus"
    DeviceNames: ["Device 7388"]
    ArchitectureName: "gfx908"

LibraryClient:
""")

# A small, gfx908-compatible MatrixInstruction grid:
#  [16, 16, 16, 1, 1, ThreadTileM, ThreadTileN, WGM, WGN]  (mfma 16)
#  [32, 32,  8, 1, 1, ThreadTileM, ThreadTileN, WGM, WGN]  (mfma 32)
# Macro tile = MFMA_M * ThreadTileM * WGM (etc).
MATRIX_INSTRUCTIONS = [
    # mfma 16x16x16i8 — flexible, smaller waves, good for skinny prefill.
    [16, 16, 16, 1, 1, 1, 1, 4, 1],  # MT 64 x 64
    [16, 16, 16, 1, 1, 2, 2, 4, 1],  # MT 128 x 128
    [16, 16, 16, 1, 1, 1, 2, 4, 1],  # MT 64 x 128
    [16, 16, 16, 1, 1, 2, 1, 4, 1],  # MT 128 x 64
    # mfma 32x32x8i8 — bigger MFMA, fewer waves; good for fat M shapes.
    [32, 32, 8, 1, 1, 1, 1, 2, 1],  # MT 64 x 64
    [32, 32, 8, 1, 1, 2, 2, 2, 1],  # MT 128 x 128
]


def render_matrix_instr_block() -> str:
    lines = []
    for mi in MATRIX_INSTRUCTIONS:
        lines.append("          - " + str(list(mi)))
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--shapes-json",
        type=Path,
        required=True,
        help="Manifest from select_w8a8_tuning_shapes.py",
    )
    ap.add_argument(
        "--out-dir", type=Path, required=True, help="Where to write per-shape YAMLs."
    )
    args = ap.parse_args()

    manifest = json.loads(args.shapes_json.read_text())
    shapes = manifest.get("shapes", [])
    args.out_dir.mkdir(parents=True, exist_ok=True)

    matrix_block = render_matrix_instr_block()
    written = []
    for s in shapes:
        M, N, K = int(s["M"]), int(s["N"]), int(s["K"])
        out = args.out_dir / f"tune_M{M}_N{N}_K{K}.yaml"
        out.write_text(
            TUNING_YAML_TMPL.format(
                M=M,
                N=N,
                K=K,
                matrix_instr_block=matrix_block,
            )
        )
        written.append(str(out))
        print(f"wrote {out}")

    index = args.out_dir / "INDEX.json"
    index.write_text(json.dumps({"yamls": written, "shapes": shapes}, indent=2))
    print(f"index: {index}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
